### ISSUE TITLE
Unable to run tpm2_create

### ISSUE THREAD

**Issue by syphernl** [electrickite/luks-tpm2#11]
If I run `./luks-tpm2 init` it tries to add a key to slot 1. It is waiting a bit on the "Sealing keyfile with the TPM" part and then fails with:

```
WARNING:esys:src/tss2-esys/api/Esys_ReadPublic.c:320:Esys_ReadPublic_Finish() Received TPM Error
ERROR:esys:src/tss2-esys/esys_tr.c:231:Esys_TR_FromTPMPublic_Finish() Error ReadPublic ErrorCode (0x0000018b)
ERROR:esys:src/tss2-esys/esys_tr.c:321:Esys_TR_FromTPMPublic() Error TR FromTPMPublic ErrorCode (0x0000018b)
ERROR: Esys_TR_FromTPMPublic(0x18B) - tpm:handle(1):the handle is not correct for the use
ERROR: Unable to run tpm2_create
```

**System:** 
- Ubuntu 20.04
- Cryptsetup 2.2.2
- tpm2-tools: 4.1.1
- Lenovo P51 with TPM 2.0

**Comment by electrickite** [comment]
Are you still seeing this error?

**Comment by electrickite** [comment]
This appears to be resolved, but feel free to reopen if you are still seeing the error.

**Comment by syphernl** [comment]
> Are you still seeing this error?

I have given up on using TPM for now (feels such cumbersome in comparison to how Bitlocker deals with it for instance) and also no longer have the aforementioned Lenovo notebook to test with unfortunately.

**Comment by u132** [comment]
Getting this same problem with Arch, cryptsetup 2.3.4, tpm2-tools 5.0, Ryzen fTPM
