### ISSUE TITLE
pacman hook

### ISSUE THREAD

**Issue by openmindead** [electrickite/luks-tpm2#2]
Here are my thoughts with regard to pacman hook for luks-tpm2:

> [Trigger]
> Operation = Install
> Operation = Upgrade
> Operation = Remove
> Type = File
> **Target = boot/vmlinuz-***
> Target = boot/intel-ucode.img
> Target = usr/lib/initcpio/*
> Target = usr/lib/systemd/boot/efi/linux*.efi.stub
> **Target = usr/share/refind/refind_x64.efi**
> 
> [Action]
> Description = Adding temporary LUKS TPM key...
> When = PostTransaction
> Exec = /usr/bin/luks-tpm2 temp

This will make it compatible with Manjaro Linux and rEFInd.

**Comment by wiktor-k** [comment]
By the way have you seen [this hook](https://aur.archlinux.org/cgit/aur.git/tree/luks-tpm2.hook?h=luks-tpm2) from [this package](https://aur.archlinux.org/packages/luks-tpm2/)?

**Comment by electrickite** [comment]
@openmindead Your suggestions have been added to the AUR package in version 0.6.0-2
